# Generated by Django 3.0.4 on 2020-03-29 01:19

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phonenumber', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('zipcode', models.CharField(max_length=5)),
                ('isPantry', models.BooleanField(null=True)),
            ],
        ),
    ]
