# Generated by Django 3.0.4 on 2020-04-23 23:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('clients', django.db.models.manager.Manager()),
            ],
        ),
    ]
